# Generated by Django 3.0.6 on 2020-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='confirmed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Confirmed Patient'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='death',
            field=models.IntegerField(blank=True, null=True, verbose_name='Death'),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='recovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Recovered patient'),
        ),
    ]
