# Generated by Django 3.0.6 on 2020-05-09 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.IntegerField(verbose_name='New Patient today')),
                ('total_patient', models.IntegerField(verbose_name='Total Patient')),
                ('died', models.IntegerField(verbose_name='Died today')),
                ('total_died', models.IntegerField(verbose_name='Total Died')),
                ('recovered', models.IntegerField(verbose_name='Recovered Today')),
                ('total_recovered', models.IntegerField(verbose_name='Total Recovered')),
                ('tested', models.IntegerField(verbose_name='Tested Today')),
                ('total_tested', models.IntegerField(verbose_name='Total Tested')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bd_bdinfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bd_bdinfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
