# Generated by Django 3.0.6 on 2020-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdinfo',
            name='died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Died today'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='patient',
            field=models.IntegerField(blank=True, null=True, verbose_name='New Patient today'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='recovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Recovered Today'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='tested',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tested Today'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='total_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Died'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='total_patient',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Patient'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='total_recovered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Recovered'),
        ),
        migrations.AlterField(
            model_name='bdinfo',
            name='total_tested',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Tested'),
        ),
    ]
